name: Latest Release Monitor  
on:
  schedule:
      - cron: 0/5 * * * *
  repository_dispatch:
      types: [trigger-latest-release-monitor]

jobs:
  main:  
    runs-on: ubuntu-latest #, node20 it don't run
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name : before Actions                              #add 24_04_01
        run : npm cache clean --force                      #add 24_04_01
          
      - name: Install Actions
                                                           #run: npm install --production --prefix ./actions --> old 
        run : npm install --save @opentelemetry/api
      - name : install Actions2
        run : npm install --save @opentelemetry/sdk-node
      - name : install Actions3
        run : npm install --save @opentelemetry/auto-instrumentations-node
      - name: Install Storage Module
        run: npm install @azure/storage-blob@12.1.1
      #- name: callLastNode                              #24_03_31 I add because 
     #   run: node20
      - name: Run Latest Release Monitor
        uses: ./actions/latest-release-monitor
        with:
          storageKey: ${{secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING}}
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}


  
 
